site:
  title: My Documentation Site
  url: https://misaki19840.github.io/document-page/
  start_page: my-docs::index.adoc
content:
  sources:
    - url: ./
      branches: main
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  overrides:
    - ./ui
