name: Build and Deploy Documentation
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'antora-playbook.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Antora
      run: npm i -g @antora/cli@2.3 @antora/site-generator-default@2.3

    - name: Build Site with Antora
      run: antora antora-playbook.yml

    - name: Install Lunr and Asciidoctor.js
      run: |
        npm install lunr asciidoctor
        node src/script.js

    # Optional: Commit search index to the repository
    - name: Commit Search Index
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add ui/search-index.json
        git commit -m "Automatically update search index"
        git push

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./build/site
