name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0  # or the version you prefer

    - name: Install Asciidoctor
      run: gem install asciidoctor

    - name: Convert AsciiDoc to HTML
      run: |
        mkdir -p output
        asciidoctor -D output src/*.adoc

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./output
